name: Build and Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main # Change this to the name of your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --prod --base-href=/tomorrow-guy/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist/tomorrow-guy
